import Head from 'next/head'

const Layout = ({ children }: { children: JSX.Element }) => {
    return (
        <div className="flex flex-col justify-center items-center">
             <Head>
                <title>SecretSanta</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="flex flex-col items-center max-w-2xl justify-center text-blue-400">
                <h1 className="text-4xl justify-center p-5">Secret Santa</h1>
                <p className="text-2xl justify-center text-center p-5">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>
            </header>
            {children}
        </div>
    )
}

export default Layout;